### ISSUE TITLE
Automate verification, promotion, decay, contradiction, and invalidation

### ISSUE THREAD

**Issue by mehrdadxzaker** [Xpounder-com/hormuz#12]
## Outcome

Make organizational memory lifecycle automatic and evidence-driven rather than a manual filing system.

## Acceptance criteria

- [ ] Raw observations are provisional and cannot become durable verified memory without configured evidence.
- [ ] Promotion rules support merged commits, passing CI, accepted reviews, approved ADRs, incident resolution, or human confirmation.
- [ ] Source hashes and repository/dependency changes trigger invalidation or confidence decay.
- [ ] Supersession preserves history and prevents stale predecessors from being selected.
- [ ] Contradictions are surfaced with both sources; they are never silently merged.
- [ ] Failed attempts become negative knowledge only after validation and cannot poison shared memory directly from a model response.
- [ ] Read permission and memory-promotion permission are distinct.
- [ ] Revalidation jobs are idempotent, resumable, observable, and tenant-scoped.
- [ ] Tests cover stale code, changed policy, reverted commit, failed CI, conflicting ADRs, malicious writeback, and recovery after a false invalidation.

**Comment by mehrdadxzaker** [comment]
Partial lifecycle milestone published in `0421afd` / PR #19.

Now implemented and verified:
- trusted versioned repository/dependency snapshots scoped to organization/repository/branch;
- immediate per-pack invalidation for mismatched explicit dependency revision/hash and mismatched `git:` source revision;
- existing supersession behavior remains order-independent and prevents active predecessors from selection;
- query-matched structured contradictions are excluded and surfaced as `requires_resolution` with both authorized source references/values;
- bounded high-confidence prompt-injection quarantine across model-visible fields;
- snapshot create/update idempotency, optimistic concurrency, integrity checks, metadata-only lifecycle audit, and SQLite v1/v2 -> v3 migration;
- REST/CLI/persistence tests and the strict 60-task benchmark-v2 release profile are green locally.

This does **not** complete #12. Still open:
- configured evidence-driven promotion for merge/CI/review/ADR/incident/human confirmation;
- automatic confidence decay and false-invalidation recovery;
- validated negative knowledge and malicious-writeback protections;
- distinct read vs promotion permissions;
- tenant-scoped, resumable, observable background revalidation jobs;
- actual source connectors and the remaining stale-policy/reverted-commit/failed-CI scenarios.

The current design deliberately persists trusted snapshots and evaluates them synchronously on every read. That provides immediate deterministic invalidation without pretending a resumable job system exists.

**Comment by mehrdadxzaker** [comment]
### Evidence-driven lifecycle checkpoint

Implemented and verified in `f7b7766` on draft PR #19.

- New managed records start provisional; existing verified records remain compatible unless Hormuz-managed evidence begins governing them.
- Configured merge, CI, review, ADR, incident, human-confirmation, and validated-failure paths can promote records; newer negative or conflicting evidence returns them to provisional.
- Evidence is tenant-, record-version-, and semantic-subject-bound. Raw external references are hashed at import and omitted from the metadata-only audit surface.
- Trusted source/dependency changes invalidate; missing observations defer; still-current evidence can recover a false invalidation without reusing evidence for changed content.
- Revalidation jobs are tenant/repository/branch scoped, resumable, lease-safe, and bound to exact snapshot, policy, record-set, and evidence-set fingerprints. New evidence after a completed run creates a new job.
- Read permission remains separate from the explicit `context_promoter` capability.

Verification:

- 213 tests passed with Codex 0.147.0 and Claude Code 2.1.233 compatibility enabled.
- The strict 60-task benchmark passed with precision, recall, and useful-pack rate 1.00 and zero safety failures.
- A clean Python 3.14 environment installed the final wheel, created context schema v4, exposed both lifecycle commands, and passed the installed benchmark smoke.
- Final local artifact hashes: wheel `57484f92c26fb31846bd549225e8f6868fdd8f719cc99185473d712543e04df2`; sdist `5c1c735b8a565b130dc8bf99c0f51c4cb4fb4d32c367bd15a3c24d134ba4aefc`.
- Push run 31929074785 and pull-request run 31929077800 each passed all seven CI jobs.

Issue #12 intentionally remains open. This checkpoint does not implement automatic Git/CI/review/ADR/incident connectors, signed attestations, probabilistic or time-based decay, hosted scheduling, PostgreSQL/multi-node leases, or automatic client injection.

**Comment by mehrdadxzaker** [comment]
Checkpoint `b1fa868` adds the provider-neutral authenticated lifecycle connector boundary on draft PR #19.

Implemented:

- `POST /v1/context/evidence`, `PUT /v1/context/lifecycle-snapshots`, and `POST /v1/context/revalidation-batches` with strict versioned contracts;
- config-independent `hormuz lifecycle evidence|snapshot|revalidate` commands for CI and internal connectors;
- authentication before body parsing, server-derived organization scope, explicit `context_promoter`, enabled-policy and batch-cap enforcement;
- bootstrap, generic workload OIDC, and opaque Hormuz bearer compatibility through the existing identity path;
- exact evidence/snapshot retry semantics, optimistic conflict responses, bounded request/response handling, redirect refusal, and safe content-free errors;
- metadata-only results/audit that omit raw evidence references and artifact identities;
- end-to-end promotion through the actual remote client without provider calls or usage-ledger events.

Evidence:

- local suite: 224 tests completed, 223 passed, one opt-in Claude executable test skipped; pinned Codex `0.147.0` and Claude Code `2.1.233` passed separately;
- strict 60-task benchmark: precision/recall/useful-pack `1.00`, zero safety failures, p95 `0.173542 ms`;
- source/wheel build, clean Python 3.14 install, installed CLI/module/benchmark smoke, source compilation, workflow parsing, and high-confidence source/extracted-wheel credential scans passed;
- push run `31930587065` and PR run `31930588090` each passed all seven jobs.

This advances but does not close #12. The connector authenticates who submitted a normalized attestation; it does not yet collect or independently verify GitHub, GitLab, CI, review, ADR, or incident events. Source-specific protocol/signature verification, signed attestations, time/confidence decay, hosted/multi-node scheduling, and mandatory context injection remain open.

**Comment by mehrdadxzaker** [comment]
## Owner decision requested: GitHub lifecycle event trust

[Proposed ADR 0005](https://github.com/Xpounder-com/hormuz/blob/mehrdad/persistent-governed-context/docs/decisions/0005-github-lifecycle-event-trust.md) is now published at [`6c70120`](https://github.com/Xpounder-com/hormuz/commit/6c70120fd89e571232dccc22e9336e70d6496a3b).

**Recommendation: option 1 — GitHub App webhook source plane plus Actions OIDC attestation plane.**

- Signed, allowlisted GitHub App webhooks establish the initial source facts for merged pull requests and completed allowlisted GitHub Actions runs.
- Actions OIDC remains a separately labeled delegated-attestation path: it proves workflow identity, not that an arbitrary submitted outcome is true.
- Tenant/repository scope comes from an administrator-bound numeric installation mapping, never the request body.
- The first app is read-only and retains normalized metadata, not raw webhook payloads.
- The first slice does not need a GitHub App private key. API polling and automated redelivery stay blocked on KMS/operations work.
- Review acceptance, revert inference, ADR/incident/human semantics, and GitHub Enterprise Server support remain outside the initial claim.

Alternatives are webhook-only, Actions-OIDC-only, or retaining manual trusted submission. The ADR records the security, replay/order, data-retention, permissions, failure, and verification boundaries for each.

Please explicitly approve option 1 (with any changes), or choose option 2, 3, or 4. Until that decision is recorded, the ADR stays Proposed and no connector implementation, app registration, webhook secret, or private key will be created.

Verification: [GitHub Actions run 31932484073](https://github.com/Xpounder-com/hormuz/actions/runs/31932484073) passed all seven jobs, including Python 3.11–3.14, package build/install, the strict governed-context benchmark, and pinned Codex plus Claude Code compatibility.

**Comment by mehrdadxzaker** [comment]
Automatic context promotion, decay, invalidation, and conflict management are knowledge/memory-product responsibilities, not Hormuz gateway responsibilities. Closing as not planned for Hormuz; #20 preserves compatibility and documentation of the earlier experiment.
